'use client'
import { Inter } from "next/font/google";
import "./globals.css";

import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { RecoilRoot } from 'recoil';
import Header from "../../components/Header/Header";

const inter = Inter({ subsets: ["latin"] });

/* export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}; */

export default function RootLayout({ children }) {
  return (
    <RecoilRoot>
      <html lang="en">
        <body className={inter.className}>
          <AppRouterCacheProvider>
            <Header />
            {children}
          </AppRouterCacheProvider>
        </body>
      </html>
    </RecoilRoot>
  );
}
